# Generated by Django 3.2.9 on 2021-11-11 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='person',
        ),
    ]
