# Generated by Django 3.2.9 on 2021-11-19 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(verbose_name='date logged')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceapp.person')),
            ],
        ),
    ]
